I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 15, in script call
    call episode2
  File "game/episode2.rpy", line 185, in script
    Диктор "Во время эфира нам поступили срочные новости."
Exception: Sayer 'Р”РёРєС‚РѕСЂ' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 15, in script call
    call episode2
  File "game/episode2.rpy", line 185, in script
    Диктор "Во время эфира нам поступили срочные новости."
  File "C:\renpy-7.1.3-sdk\renpy\ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\renpy-7.1.3-sdk\renpy\ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'Р”РёРєС‚РѕСЂ' is not defined.

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
Winter Friend Story 1.0
Mon Dec 31 14:47:15 2018
