I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script call
    call episode1
  File "game/episode1.rpy", line 32, in script
    play sound vk
  File "renpy/common/000statements.rpy", line 268, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/episode1.rpy", line 32, in <module>
    play sound vk
NameError: name 'vk' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script call
    call episode1
  File "game/episode1.rpy", line 32, in script
    play sound vk
  File "C:\renpy-7.1.3-sdk\renpy\ast.py", line 1861, in execute
    self.call("execute")
  File "C:\renpy-7.1.3-sdk\renpy\ast.py", line 1849, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\renpy-7.1.3-sdk\renpy\statements.py", line 203, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 268, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "C:\renpy-7.1.3-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\renpy-7.1.3-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/episode1.rpy", line 32, in <module>
    play sound vk
NameError: name 'vk' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
Winter Friend Story 1.0
Mon Dec 31 14:03:54 2018
